[general]
import = [ "./tokyonight.toml" ]

[window]
padding = { x = 10, y = 10 }
opacity = 0.8

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

[mouse]
hide_when_typing = true
